# Generated by Django 2.1.7 on 2019-04-07 03:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('removed', models.BooleanField(default=False)),
                ('created_time', models.DateTimeField(default=datetime.datetime(2019, 4, 7, 3, 57, 57, 338044, tzinfo=utc))),
                ('removed1', models.NullBooleanField(default=False)),
            ],
            options={
                'db_table': 'article',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('del_field', models.IntegerField(blank=True, db_column='del', null=True)),
            ],
            options={
                'db_table': 'business',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ChannelSettings',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('device_id', models.CharField(blank=True, max_length=255, null=True)),
                ('channel_index', models.IntegerField(blank=True, null=True)),
                ('channel_type', models.IntegerField(blank=True, null=True)),
                ('channel_alias', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'channel_settings',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('province_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('del_field', models.IntegerField(blank=True, db_column='del', null=True)),
                ('sys_code', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'city',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CollectorManagerSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ping', models.DateTimeField(blank=True, null=True)),
                ('online', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'collector_manager_settings',
                'managed': True,
            },
        ),
    ]
