# Generated by Django 2.1.7 on 2019-04-03 01:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('removed', models.BooleanField(default=False)),
                ('created_time', models.DateTimeField(default=datetime.datetime(2019, 4, 3, 1, 27, 59, 271311, tzinfo=utc))),
                ('removed1', models.NullBooleanField(default=False)),
            ],
            options={
                'db_table': 'article',
            },
        ),
    ]
