# Generated by Django 2.1.7 on 2019-04-07 04:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190407_0415'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailoffer',
            options={'managed': True},
        ),
        migrations.AddField(
            model_name='emailoffer',
            name='own_company',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AlterField(
            model_name='article',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 7, 4, 27, 55, 598030, tzinfo=utc)),
        ),
        migrations.AlterModelTable(
            name='emailoffer',
            table='email_offer',
        ),
    ]
